"""Add main_genre to Author

Revision ID: 19546187ba15
Revises: 6f18be629133
Create Date: 2025-10-06 10:43:32.085429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19546187ba15'
down_revision = '6f18be629133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_genre', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_column('main_genre')

    # ### end Alembic commands ###
