"""Add mail and phone number to Borrowings

Revision ID: 8f52126ee56f
Revises: d1845d03fe10
Create Date: 2025-09-28 10:10:59.054707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f52126ee56f'
down_revision = 'd1845d03fe10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowings', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
